name: Test Codebase

on:
  pull_request:
    branches: [ master, dev ]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ feature/projects ]
permissions:
  contents: read

jobs:
  start:
    name: Start State 🚀🚀🚀
    runs-on: ubuntu-latest
    steps:
    - name: Starting
      id: init
      run: |
        echo "Starting linting of ${{ github.repository }}"

  run_all_tests:
    name: Run all Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    needs: start
    steps:
      - name: Checkout for ${{ runner.os }}
        uses: actions/checkout@v3

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Run unit/integration tests and collect coverage
        run: npm run test
        env:
          CI: true

      - name: Upload coverage to Codecov
        if: ${{ runner.os == 'macOS' }}
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

    timeout-minutes: 20

  end:
    name: End State ✅✅✅
    runs-on: ubuntu-latest
    needs: run_all_tests
    steps:
    - name: Ending
      id: init
      run: |
        echo "Ending linting of ${{ github.repository }}"